# Codex Quota Keeper - one-shot expiry alarm adapter for Windows Task Scheduler.
# The pure plan function is the test surface; the adapter only wakes runner.ps1.

$script:CqkAnchorAlarmDir = Split-Path -Parent $PSCommandPath
if (-not (Get-Command Get-KeeperRoot -ErrorAction SilentlyContinue)) {
    . (Join-Path $script:CqkAnchorAlarmDir 'common.ps1')
}
if (-not (Get-Command Get-BucketWindowMap -ErrorAction SilentlyContinue)) {
    . (Join-Path $script:CqkAnchorAlarmDir 'state-machine.ps1')
}

function Get-AnchorAlarmTaskName {
    param([hashtable]$Config)
    if ($Config.task -is [hashtable] -and -not [string]::IsNullOrWhiteSpace([string]$Config.task.alarmName)) {
        return [string]$Config.task.alarmName
    }
    return ([string]$Config.task.name + '.AnchorAlarm')
}

function Get-AnchorAlarmPlan {
    param([hashtable]$Config, [hashtable]$State, [DateTime]$Now = (Get-Date))
    $name = Get-AnchorAlarmTaskName $Config
    $aa = Get-AutoAnchorConfig $Config
    if (-not (Test-AutoAnchorArmed $Config) -or @($aa.anchorOnExpiry).Count -eq 0) {
        return @{ action = 'clear'; taskName = $name; targetEpoch = $null; targetAt = $null; reason = 'expiry anchoring is not armed' }
    }
    $nowEpoch = ConvertTo-EpochSeconds $Now
    $targets = @()
    foreach ($win in @((Get-BucketWindowMap @($State.buckets)).Values)) {
        if ([string]$win.windowType -notin @($aa.anchorOnExpiry)) { continue }
        if ($null -ne $win.resetsAt -and [long]$win.resetsAt -gt $nowEpoch) { $targets += [long]$win.resetsAt }
    }
    if ($targets.Count -eq 0) {
        return @{ action = 'clear'; taskName = $name; targetEpoch = $null; targetAt = $null; reason = 'no future tracked expiry' }
    }
    $targetEpoch = [long](($targets | Measure-Object -Minimum).Minimum) + 60
    return @{
        action = 'set'; taskName = $name; targetEpoch = $targetEpoch
        targetAt = ConvertFrom-EpochSeconds $targetEpoch
        reason = 'earliest tracked expiry plus one minute'
    }
}

function Get-AnchorAlarmLauncherSpec {
    param([string]$KeeperRoot, [string]$ConfigFile)
    $root = Get-KeeperRoot $KeeperRoot
    if (-not $ConfigFile) { $ConfigFile = Get-ConfigPath $root }
    $pwsh = Get-Command pwsh -ErrorAction SilentlyContinue
    if (-not $pwsh) { $pwsh = Get-Command powershell -ErrorAction SilentlyContinue }
    $wscript = Get-Command wscript -ErrorAction SilentlyContinue
    if (-not $pwsh -or -not $wscript) { throw 'PowerShell and wscript.exe are required for the expiry alarm task' }
    $runner = Join-Path $root 'scripts\runner.ps1'
    $inner = ('"{0}" -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File "{1}" -KeeperRoot "{2}" -ConfigFile "{3}" -FromAlarm -WaitLockSeconds 60' -f `
        $pwsh.Source, $runner, $root, [System.IO.Path]::GetFullPath($ConfigFile))
    $runtimeDir = Join-Path $root 'runtime'
    Ensure-Directory $runtimeDir | Out-Null
    $vbsPath = Join-Path $runtimeDir 'hidden-launch-anchor-alarm.vbs'
    $lines = @(
        "' Generated by Codex Quota Keeper - do not edit."
        ('CreateObject("WScript.Shell").Run "{0}", 0, False' -f ($inner -replace '"', '""'))
    )
    [System.IO.File]::WriteAllText($vbsPath, ($lines -join "`r`n") + "`r`n", (New-Object System.Text.UTF8Encoding($false)))
    return @{ exe = $wscript.Source; arguments = '"{0}"' -f $vbsPath; innerCommand = $inner; vbsPath = $vbsPath }
}

function Sync-AnchorAlarmTask {
    param([hashtable]$Config, [hashtable]$State, [string]$KeeperRoot, [string]$ConfigFile, [DateTime]$Now = (Get-Date))
    $plan = Get-AnchorAlarmPlan -Config $Config -State $State -Now $Now
    try {
        $existing = Get-ScheduledTask -TaskName $plan.taskName -ErrorAction SilentlyContinue
        if ($plan.action -eq 'clear') {
            if ($existing) {
                Unregister-ScheduledTask -TaskName $plan.taskName -Confirm:$false
                return @{ ok = $true; changed = $true; event = 'ANCHOR_ALARM_CLEARED'; taskName = $plan.taskName; targetAt = $null; reason = $plan.reason }
            }
            return @{ ok = $true; changed = $false; event = $null; taskName = $plan.taskName; targetAt = $null; reason = $plan.reason }
        }

        $launcher = Get-AnchorAlarmLauncherSpec -KeeperRoot $KeeperRoot -ConfigFile $ConfigFile
        $action = New-ScheduledTaskAction -Execute $launcher.exe -Argument $launcher.arguments -WorkingDirectory (Get-KeeperRoot $KeeperRoot)
        $trigger = New-ScheduledTaskTrigger -Once -At $plan.targetAt
        $settingsParams = @{
            MultipleInstances = 'IgnoreNew'; ExecutionTimeLimit = (Get-KeeperTaskExecutionTimeLimit $Config).timeSpan
            StartWhenAvailable = $true; AllowStartIfOnBatteries = $true; DontStopIfGoingOnBatteries = $true
        }
        if ($Config.task.wakeToRun -eq $true) { $settingsParams.WakeToRun = $true }
        if ($Config.task.runIfNetworkAvailable -eq $true) { $settingsParams.RunOnlyIfNetworkAvailable = $true }
        $settings = New-ScheduledTaskSettingsSet @settingsParams
        $principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive -RunLevel Limited
        Register-ScheduledTask -TaskName $plan.taskName -Action $action -Trigger $trigger -Settings $settings `
            -Principal $principal -Description 'Codex Quota Keeper: wake runner at the earliest tracked quota-window expiry.' -Force | Out-Null
        return @{ ok = $true; changed = $true; event = 'ANCHOR_ALARM_SET'; taskName = $plan.taskName; targetAt = $plan.targetAt; reason = $plan.reason }
    } catch {
        return @{ ok = $false; changed = $false; event = $null; taskName = $plan.taskName; targetAt = $plan.targetAt; reason = (Hide-SensitiveText $_.Exception.Message) }
    }
}
