# Codex Quota Keeper - installer (doc 03 §4).
# Validates the environment, runs a read-only quota probe, generates the machine
# identity and registers a per-user Scheduled Task. No admin rights required.

param(
    [string]$KeeperRoot = '',
    [string]$ConfigFile = '',
    [switch]$SkipProbe
)

$script:CqkInstallDir = Split-Path -Parent $PSCommandPath
if (-not (Get-Command Get-KeeperRoot -ErrorAction SilentlyContinue)) {
    . (Join-Path $script:CqkInstallDir 'common.ps1')
}
if (-not (Get-Command Invoke-Preflight -ErrorAction SilentlyContinue)) {
    . (Join-Path $script:CqkInstallDir 'preflight.ps1')
}
if (-not (Get-Command Invoke-CodexRateLimitsRead -ErrorAction SilentlyContinue)) {
    . (Join-Path $script:CqkInstallDir 'quota-client.ps1')
}

function Get-KeeperPowerShellPath {
    $pwsh = Get-Command pwsh -ErrorAction SilentlyContinue
    if ($pwsh) { return $pwsh.Source }
    return (Get-Command powershell -ErrorAction SilentlyContinue).Source
}

function Get-KeeperWscriptPath {
    # wscript.exe lives in System32; hard fail late if missing (never seen in practice).
    return (Get-Command wscript -ErrorAction SilentlyContinue).Source
}

function Write-KeeperHiddenLauncherVbs {
    # Scheduled task actions that execute powershell.exe directly still flash a
    # console for a few hundred ms (conhost is created before -WindowStyle Hidden
    # applies). Launching via wscript.exe + a generated .vbs (Run(..., 0, False))
    # keeps the window hidden from creation, eliminating the flash. Idempotent:
    # rewritten on every install/apply-config.
    param([string]$KeeperRoot, [string]$InnerCommand, [string]$Name)
    $runtimeDir = Join-Path (Get-KeeperRoot $KeeperRoot) 'runtime'
    Ensure-Directory $runtimeDir | Out-Null
    $vbsPath = Join-Path $runtimeDir $Name
    $lines = @(
        "' Generated by Codex Quota Keeper install - do not edit (regenerated on apply-config)."
        ('CreateObject("WScript.Shell").Run "{0}", 0, False' -f ($InnerCommand -replace '"', '""'))
    )
    # WScript.Shell.Run takes its command as one quoted string; doubling embedded
    # quotes is the VBS escaping rule.
    [System.IO.File]::WriteAllText($vbsPath, ($lines -join "`r`n") + "`r`n", (New-Object System.Text.UTF8Encoding($false)))
    return $vbsPath
}

function Get-KeeperHiddenLauncherSpec {
    # Builds the wscript launch spec for the scheduled poll (or a forced anchor
    # when -ForceAnchorSwitch is given). Pure construction besides writing the
    # generated .vbs under runtime\.
    param(
        [string]$KeeperRoot,
        [string]$ConfigFile = '',
        [switch]$ForceAnchorSwitch
    )
    $pwsh = Get-KeeperPowerShellPath
    if (-not $pwsh) { throw 'no PowerShell executable found for the task action' }
    $wscript = Get-KeeperWscriptPath
    if (-not $wscript) { throw 'wscript.exe not found for hidden task launch' }
    $root = Get-KeeperRoot $KeeperRoot
    $runner = Join-Path $root 'scripts\runner.ps1'
    # CQK-022: pin the exact config file the installer validated against into the
    # task command line. Without -ConfigFile the scheduled runner silently falls
    # back to <KeeperRoot>\config.json, so a custom -ConfigFile would be honored
    # once at install time and ignored on every poll afterwards.
    if (-not $ConfigFile) { $ConfigFile = Get-ConfigPath $root }
    $inner = ('"{0}" -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File "{1}" -KeeperRoot "{2}" -ConfigFile "{3}"' -f `
        $pwsh, $runner, $root, [System.IO.Path]::GetFullPath($ConfigFile))
    if ($ForceAnchorSwitch) { $inner = "$inner -ForceAnchor" }
    $name = if ($ForceAnchorSwitch) { 'hidden-launch-forced-anchor.vbs' } else { 'hidden-launch.vbs' }
    $vbsPath = Write-KeeperHiddenLauncherVbs -KeeperRoot $KeeperRoot -InnerCommand $inner -Name $name
    return @{ exe = $wscript; arguments = '"{0}"' -f $vbsPath; vbsPath = $vbsPath; innerCommand = $inner }
}

function New-KeeperTaskParameters {
    # Builds the Register-/Set-ScheduledTask parameter objects. Pure construction
    # (no registration) so tests can inspect trigger/settings without touching
    # the real Task Scheduler.
    param([hashtable]$Config, [string]$KeeperRoot, [string]$ConfigFile = '')
    $runner = Join-Path (Get-KeeperRoot $KeeperRoot) 'scripts\runner.ps1'

    # wscript + generated .vbs: keeps the console hidden from creation (no flash
    # on every scheduled run, unlike launching powershell.exe directly).
    $launcher = Get-KeeperHiddenLauncherSpec -KeeperRoot $KeeperRoot -ConfigFile $ConfigFile
    $action = New-ScheduledTaskAction -Execute $launcher.exe `
        -Argument $launcher.arguments `
        -WorkingDirectory (Get-KeeperRoot $KeeperRoot)

    $interval = New-TimeSpan -Minutes (Get-PollConfig $Config).intervalMinutes
    # 3650 days: [TimeSpan]::MaxValue generates out-of-range XML on current
    # Windows builds; 10 years is accepted and effectively indefinite for a poller.
    $trigger = New-ScheduledTaskTrigger -Once -At (Get-Date).AddMinutes(1) -RepetitionInterval $interval -RepetitionDuration (New-TimeSpan -Days 3650)
    if ($Config.task.startWithWindows -eq $true) {
        $logonTrigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
        $triggers = @($trigger, $logonTrigger)
    } else {
        $triggers = @($trigger)
    }

    $settingsParams = @{
        MultipleInstances           = 'IgnoreNew'
        # CQK-031: derived from the config, not a fixed 15 min. A large
        # queryTimeoutSeconds (or an AutoAnchor exec) needs more than 15 min; a
        # short poll must not be swamped by a limit that outlives the next trigger.
        ExecutionTimeLimit          = (Get-KeeperTaskExecutionTimeLimit $Config).timeSpan
        StartWhenAvailable          = $true
        AllowStartIfOnBatteries     = $true
        DontStopIfGoingOnBatteries  = $true
    }
    if ($Config.task.wakeToRun -eq $true) { $settingsParams.WakeToRun = $true }
    if ($Config.task.runIfNetworkAvailable -eq $true) { $settingsParams.RunOnlyIfNetworkAvailable = $true }
    $settings = New-ScheduledTaskSettingsSet @settingsParams

    $principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive -RunLevel Limited

    return @{
        TaskName  = [string]$Config.task.name
        Action    = $action
        Trigger   = $triggers
        Settings  = $settings
        Principal = $principal
        # CQK-032: the description shown in Task Scheduler has to state what the
        # task actually does. Hardcoding "MonitorOnly" told AutoAnchor users their
        # task was read-only polling, which is the one thing the experimental
        # anchoring mode is not.
        Description = Get-KeeperTaskDescription -Config $Config
    }
}

function Get-KeeperTaskDescription {
    # One line for the Task Scheduler UI, derived from the effective behaviour:
    # mode + whether anchoring is really armed (mode=AutoAnchor alone is not
    # enough - the runner only anchors when codex.autoAnchor.enabled=true). The
    # configured mode is echoed either way, so a mode=AutoAnchor config with
    # anchoring disarmed reads as "polling only, AutoAnchor mode" instead of
    # claiming a mode the config does not have.
    param([hashtable]$Config)
    $mode = if ($Config) { [string]$Config.mode } else { 'MonitorOnly' }
    if ([string]::IsNullOrWhiteSpace($mode)) { $mode = 'MonitorOnly' }
    $anchoring = ($mode -eq 'AutoAnchor') -and (Test-AutoAnchorEnabled $Config)
    if ($anchoring) {
        return 'Codex Quota Keeper: scheduled Codex quota polling + EXPERIMENTAL auto-anchoring (AutoAnchor). One-shot runner, never resident.'
    }
    return "Codex Quota Keeper: scheduled read-only Codex quota polling (mode=$mode). One-shot runner, never resident."
}

function Get-ForcedAnchorLaunchSpec {
    # codex.autoAnchor.anchorOnApply=true: build the one-shot runner launch that
    # forces a CLI anchor right away (no waiting for keepalive or a reset). The
    # runner applies its own guards (daily cap, fail-closed errors, local lock).
    # Pure construction so tests can inspect it without spawning a process.
    param([hashtable]$Config, [string]$KeeperRoot, [string]$ConfigFile)
    $aa = Get-AutoAnchorConfig $Config
    if (-not $aa.enabled) { return @{ skip = $true; reason = 'codex.autoAnchor not enabled'; exe = $null; arguments = $null } }
    if ($aa.anchorOnApply -ne $true) { return @{ skip = $true; reason = 'anchorOnApply not enabled'; exe = $null; arguments = $null } }
    try {
        $launcher = Get-KeeperHiddenLauncherSpec -KeeperRoot $KeeperRoot -ConfigFile $ConfigFile -ForceAnchorSwitch
    } catch {
        return @{ skip = $true; reason = $_.Exception.Message; exe = $null; arguments = $null }
    }
    return @{
        skip = $false; reason = $null; exe = $launcher.exe
        arguments = $launcher.arguments; vbsPath = $launcher.vbsPath; innerCommand = $launcher.innerCommand
    }
}

function Invoke-ForcedAnchorIfRequested {
    # Fire and forget a runner with -ForceAnchor when the config asks for it.
    # A start failure is reported but never fails install/apply-config.
    param([hashtable]$Config, [string]$KeeperRoot, [string]$ConfigFile)
    $spec = Get-ForcedAnchorLaunchSpec -Config $Config -KeeperRoot $KeeperRoot -ConfigFile $ConfigFile
    if ($spec.skip) { return @{ started = $false; reason = $spec.reason } }
    try {
        # wscript is windowless by itself; no -WindowStyle needed (and it would be ignored).
        Start-Process -FilePath $spec.exe -ArgumentList $spec.arguments
        return @{ started = $true; reason = $null }
    } catch {
        return @{ started = $false; reason = $_.Exception.Message }
    }
}

function Register-KeeperTask {
    param([hashtable]$Config, [string]$KeeperRoot, [string]$ConfigFile = '')
    $tp = New-KeeperTaskParameters -Config $Config -KeeperRoot $KeeperRoot -ConfigFile $ConfigFile
    Register-ScheduledTask -TaskName $tp.TaskName `
        -Action $tp.Action -Trigger $tp.Trigger -Settings $tp.Settings `
        -Principal $tp.Principal -Description $tp.Description -Force | Out-Null
    return $tp.TaskName
}

function Invoke-KeeperInstall {
    # Returns @{ ok; issues; taskName; machine; probe; codexPath }
    param(
        [string]$KeeperRoot = '',
        [string]$ConfigFile = '',
        [switch]$SkipProbe
    )
    $issues = @()
    if (-not $KeeperRoot) { $KeeperRoot = Get-KeeperRoot }
    if (-not $ConfigFile) { $ConfigFile = Get-ConfigPath $KeeperRoot }

    # 1. Environment validation (PS version, git, codex, repo whitelist, runtime).
    $pf = Invoke-Preflight -Config $null -ConfigPath $ConfigFile -KeeperRoot $KeeperRoot
    if ($null -eq $pf -or -not $pf.machine) {
        return @{ ok = $false; issues = @('preflight failed before producing a machine identity'); taskName = $null; machine = $null; probe = $null; codexPath = $null }
    }
    $issues += $pf.issues
    if ($PSVersionTable.PSVersion.Major -lt 5) {
        $issues += 'PowerShell 5.1 or newer is required'
    }

    # 2. Read-only connectivity probe (never calls the model).
    $probe = $null
    if (-not $SkipProbe -and $pf.codexPath) {
        $loaded = Load-Config $ConfigFile
        $probe = Invoke-CodexRateLimitsRead -Config $loaded.config -CodexPath $pf.codexPath
        if (-not $probe.ok) {
            $issues += "quota probe failed ($($probe.errorKind)): $($probe.message)"
        }
    }

    if ($issues.Count -gt 0) {
        return @{ ok = $false; issues = $issues; taskName = $null; machine = $pf.machine; probe = $probe; codexPath = $pf.codexPath }
    }

    # 3. Machine identity already ensured by preflight (random UUID + label).

    # 4/5. Register the per-user scheduled task.
    $loaded = Load-Config $ConfigFile
    $taskName = Register-KeeperTask -Config $loaded.config -KeeperRoot $KeeperRoot -ConfigFile $ConfigFile
    $forcedAnchor = Invoke-ForcedAnchorIfRequested -Config $loaded.config -KeeperRoot $KeeperRoot -ConfigFile $ConfigFile

    return @{ ok = $true; issues = @(); taskName = $taskName; machine = $pf.machine; probe = $probe; codexPath = $pf.codexPath; forcedAnchor = $forcedAnchor }
}

# Direct execution (pwsh -File / install.cmd): run the install interactively.
if ($MyInvocation.InvocationName -ne '.') {
    $result = Invoke-KeeperInstall -KeeperRoot $KeeperRoot -ConfigFile $ConfigFile -SkipProbe:$SkipProbe
    Write-Host 'Codex Quota Keeper - Install'
    Write-Host '========================================'
    foreach ($i in $result.issues) { Write-Host "  [ISSUE] $i" -ForegroundColor Yellow }
    if ($result.ok) {
        Write-Host "  Installed        : YES (task '$($result.taskName)')"
        Write-Host "  Machine identity : $($result.machine.label) [$($result.machine.machineId)]"
        Write-Host "  Quota probe      : $(if ($SkipProbe) { 'SKIPPED (-SkipProbe)' } else { 'OK (read-only, no model call)' })"
        Write-Host "  Forced anchor    : $(if ($result.forcedAnchor.started) { 'STARTED (codex.autoAnchor.anchorOnApply=true)' } else { "no ($($result.forcedAnchor.reason))" })"
        Write-Host ''
        Write-Host '  Next: double-click status.cmd to verify.'
    } else {
        Write-Host '  Installed        : NO (fix the issues above and re-run)' -ForegroundColor Red
    }
    exit $(if ($result.ok) { 0 } else { 1 })
}
