# Codex Quota Keeper - installer (doc 03 §4).
# Validates the environment, runs a read-only quota probe, generates the machine
# identity and registers a per-user Scheduled Task. No admin rights required.

param(
    [string]$KeeperRoot = '',
    [string]$ConfigFile = '',
    [switch]$SkipProbe,
    [switch]$Detailed
)

$script:CqkInstallDir = Split-Path -Parent $PSCommandPath
if (-not (Get-Command Get-KeeperRoot -ErrorAction SilentlyContinue)) {
    . (Join-Path $script:CqkInstallDir 'common.ps1')
}
if (-not (Get-Command Invoke-Preflight -ErrorAction SilentlyContinue)) {
    . (Join-Path $script:CqkInstallDir 'preflight.ps1')
}
if (-not (Get-Command Invoke-CodexRateLimitsRead -ErrorAction SilentlyContinue)) {
    . (Join-Path $script:CqkInstallDir 'quota-client.ps1')
}
if (-not (Get-Command Resolve-ExecutionProfile -ErrorAction SilentlyContinue)) {
    . (Join-Path $script:CqkInstallDir 'codex-profile.ps1')
}

function Get-KeeperPowerShellPath {
    $pwsh = Get-Command pwsh -ErrorAction SilentlyContinue
    if ($pwsh) { return $pwsh.Source }
    return (Get-Command powershell -ErrorAction SilentlyContinue).Source
}

function Get-KeeperWscriptPath {
    # wscript.exe lives in System32; hard fail late if missing (never seen in practice).
    return (Get-Command wscript -ErrorAction SilentlyContinue).Source
}

function Write-KeeperHiddenLauncherVbs {
    # Scheduled task actions that execute powershell.exe directly still flash a
    # console for a few hundred ms (conhost is created before -WindowStyle Hidden
    # applies). Launching via wscript.exe + a generated .vbs (Run(..., 0, False))
    # keeps the window hidden from creation, eliminating the flash. Idempotent:
    # rewritten on every install/apply-config.
    param([string]$KeeperRoot, [string]$InnerCommand, [string]$Name)
    $runtimeDir = Join-Path (Get-KeeperRoot $KeeperRoot) 'runtime'
    Ensure-Directory $runtimeDir | Out-Null
    $vbsPath = Join-Path $runtimeDir $Name
    $lines = @(
        "' Generated by Codex Quota Keeper install - do not edit (regenerated on apply-config)."
        ('CreateObject("WScript.Shell").Run "{0}", 0, False' -f ($InnerCommand -replace '"', '""'))
    )
    # WScript.Shell.Run takes its command as one quoted string; doubling embedded
    # quotes is the VBS escaping rule.
    [System.IO.File]::WriteAllText($vbsPath, ($lines -join "`r`n") + "`r`n", (New-Object System.Text.UTF8Encoding($false)))
    return $vbsPath
}

function Get-KeeperHiddenLauncherSpec {
    # Builds the wscript launch spec for the scheduled poll (or a forced anchor
    # when -ForceAnchorSwitch is given). Pure construction besides writing the
    # generated .vbs under runtime\.
    param(
        [string]$KeeperRoot,
        [string]$ConfigFile = '',
        [switch]$ForceAnchorSwitch
    )
    $pwsh = Get-KeeperPowerShellPath
    if (-not $pwsh) { throw 'no PowerShell executable found for the task action' }
    $wscript = Get-KeeperWscriptPath
    if (-not $wscript) { throw 'wscript.exe not found for hidden task launch' }
    $root = Get-KeeperRoot $KeeperRoot
    $runner = Join-Path $root 'scripts\runner.ps1'
    # CQK-022: pin the exact config file the installer validated against into the
    # task command line. Without -ConfigFile the scheduled runner silently falls
    # back to <KeeperRoot>\config.json, so a custom -ConfigFile would be honored
    # once at install time and ignored on every poll afterwards.
    if (-not $ConfigFile) { $ConfigFile = Get-ConfigPath $root }
    $inner = ('"{0}" -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File "{1}" -KeeperRoot "{2}" -ConfigFile "{3}"' -f `
        $pwsh, $runner, $root, [System.IO.Path]::GetFullPath($ConfigFile))
    if ($ForceAnchorSwitch) { $inner = "$inner -ForceAnchor" }
    $name = if ($ForceAnchorSwitch) { 'hidden-launch-forced-anchor.vbs' } else { 'hidden-launch.vbs' }
    $vbsPath = Write-KeeperHiddenLauncherVbs -KeeperRoot $KeeperRoot -InnerCommand $inner -Name $name
    return @{ exe = $wscript; arguments = '"{0}"' -f $vbsPath; vbsPath = $vbsPath; innerCommand = $inner }
}

function New-KeeperTaskParameters {
    # Builds the Register-/Set-ScheduledTask parameter objects. Pure construction
    # (no registration) so tests can inspect trigger/settings without touching
    # the real Task Scheduler.
    param([hashtable]$Config, [string]$KeeperRoot, [string]$ConfigFile = '')
    $runner = Join-Path (Get-KeeperRoot $KeeperRoot) 'scripts\runner.ps1'

    # wscript + generated .vbs: keeps the console hidden from creation (no flash
    # on every scheduled run, unlike launching powershell.exe directly).
    $launcher = Get-KeeperHiddenLauncherSpec -KeeperRoot $KeeperRoot -ConfigFile $ConfigFile
    $action = New-ScheduledTaskAction -Execute $launcher.exe `
        -Argument $launcher.arguments `
        -WorkingDirectory (Get-KeeperRoot $KeeperRoot)

    $interval = New-TimeSpan -Minutes (Get-PollConfig $Config).intervalMinutes
    # 3650 days: [TimeSpan]::MaxValue generates out-of-range XML on current
    # Windows builds; 10 years is accepted and effectively indefinite for a poller.
    $trigger = New-ScheduledTaskTrigger -Once -At (Get-Date).AddMinutes(1) -RepetitionInterval $interval -RepetitionDuration (New-TimeSpan -Days 3650)
    if ($Config.task.startWithWindows -eq $true) {
        $logonTrigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
        $triggers = @($trigger, $logonTrigger)
    } else {
        $triggers = @($trigger)
    }

    $settingsParams = @{
        MultipleInstances           = 'IgnoreNew'
        # CQK-031: derived from the config, not a fixed 15 min. A large
        # queryTimeoutSeconds (or an AutoAnchor exec) needs more than 15 min; a
        # short poll must not be swamped by a limit that outlives the next trigger.
        ExecutionTimeLimit          = (Get-KeeperTaskExecutionTimeLimit $Config).timeSpan
        StartWhenAvailable          = $true
        AllowStartIfOnBatteries     = $true
        DontStopIfGoingOnBatteries  = $true
    }
    if ($Config.task.wakeToRun -eq $true) { $settingsParams.WakeToRun = $true }
    if ($Config.task.runIfNetworkAvailable -eq $true) { $settingsParams.RunOnlyIfNetworkAvailable = $true }
    $settings = New-ScheduledTaskSettingsSet @settingsParams

    $principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive -RunLevel Limited

    return @{
        TaskName  = [string]$Config.task.name
        Action    = $action
        Trigger   = $triggers
        Settings  = $settings
        Principal = $principal
        # CQK-032: the description shown in Task Scheduler has to state what the
        # task actually does. Hardcoding "MonitorOnly" told AutoAnchor users their
        # task was read-only polling, which is the one thing the experimental
        # anchoring mode is not.
        Description = Get-KeeperTaskDescription -Config $Config
    }
}

function Get-KeeperTaskDescription {
    # One line for the Task Scheduler UI, derived from the effective behaviour:
    # mode + whether anchoring is really armed (mode=AutoAnchor alone is not
    # enough - the runner only anchors when codex.autoAnchor.enabled=true). The
    # configured mode is echoed either way, so a mode=AutoAnchor config with
    # anchoring disarmed reads as "polling only, AutoAnchor mode" instead of
    # claiming a mode the config does not have.
    param([hashtable]$Config)
    $mode = if ($Config) { [string]$Config.mode } else { 'MonitorOnly' }
    if ([string]::IsNullOrWhiteSpace($mode)) { $mode = 'MonitorOnly' }
    $anchoring = Test-AutoAnchorArmed $Config
    if ($anchoring) {
        return 'Codex Quota Keeper: scheduled Codex quota polling + EXPERIMENTAL auto-anchoring (AutoAnchor). One-shot runner, never resident.'
    }
    return "Codex Quota Keeper: scheduled read-only Codex quota polling (mode=$mode). One-shot runner, never resident."
}

function Get-ForcedAnchorLaunchSpec {
    # codex.autoAnchor.anchorOnApply=true: build the one-shot runner launch that
    # forces a CLI anchor right away (no waiting for keepalive or a reset). The
    # runner applies its own guards (daily cap, fail-closed errors, local lock).
    # Pure construction so tests can inspect it without spawning a process.
    param([hashtable]$Config, [string]$KeeperRoot, [string]$ConfigFile)
    $aa = Get-AutoAnchorConfig $Config
    if (-not $aa.enabled) { return @{ skip = $true; reason = 'codex.autoAnchor not enabled'; exe = $null; arguments = $null } }
    if ($aa.anchorOnApply -ne $true) { return @{ skip = $true; reason = 'anchorOnApply not enabled'; exe = $null; arguments = $null } }
    try {
        $launcher = Get-KeeperHiddenLauncherSpec -KeeperRoot $KeeperRoot -ConfigFile $ConfigFile -ForceAnchorSwitch
    } catch {
        return @{ skip = $true; reason = $_.Exception.Message; exe = $null; arguments = $null }
    }
    return @{
        skip = $false; reason = $null; exe = $launcher.exe
        arguments = $launcher.arguments; vbsPath = $launcher.vbsPath; innerCommand = $launcher.innerCommand
    }
}

function Invoke-ForcedAnchorIfRequested {
    # Fire and forget a runner with -ForceAnchor when the config asks for it.
    # A start failure is reported but never fails install/apply-config.
    param([hashtable]$Config, [string]$KeeperRoot, [string]$ConfigFile)
    $spec = Get-ForcedAnchorLaunchSpec -Config $Config -KeeperRoot $KeeperRoot -ConfigFile $ConfigFile
    if ($spec.skip) { return @{ started = $false; reason = $spec.reason } }
    try {
        # wscript is windowless by itself; no -WindowStyle needed (and it would be ignored).
        Start-Process -FilePath $spec.exe -ArgumentList $spec.arguments
        return @{ started = $true; reason = $null }
    } catch {
        return @{ started = $false; reason = $_.Exception.Message }
    }
}

function Register-KeeperTask {
    param([hashtable]$Config, [string]$KeeperRoot, [string]$ConfigFile = '')
    $tp = New-KeeperTaskParameters -Config $Config -KeeperRoot $KeeperRoot -ConfigFile $ConfigFile
    Register-ScheduledTask -TaskName $tp.TaskName `
        -Action $tp.Action -Trigger $tp.Trigger -Settings $tp.Settings `
        -Principal $tp.Principal -Description $tp.Description -Force | Out-Null
    return $tp.TaskName
}

function Get-ExecutionProfileGate {
    # doc v3.0 §7: strong semantic validation is NOT a universal blocker. The gate
    # only bites when AutoAnchor is genuinely armed (mode=AutoAnchor AND
    # codex.autoAnchor.enabled=true), because that is the only state where a model
    # call is actually going to happen:
    #
    #   mode=MonitorOnly                  -> warning only (read-only install stands)
    #   mode=AutoAnchor + enabled=false   -> warning only (no model runs today)
    #   mode=AutoAnchor + enabled=true    -> INVALID or UNAVAILABLE blocks
    #
    # UNAVAILABLE blocks too when armed: "could not check" is not "checked and
    # fine", and an unattended keeper must fail closed rather than anchor on an
    # unverified profile.
    #
    # The resolution is LIVE (one app-server session: config/read + the full
    # model/list) rather than reused from preflight, because §6.2 requires the
    # profile to be read in the same Codex environment `codex exec` will use.
    #
    # Returns @{ attempted; armed; validation; profile; issues; warnings; cache }.
    # `issues` is what a caller appends to its blocking list; `warnings` is a
    # SEPARATE list on purpose - a MonitorOnly config with a typo'd model must not
    # become un-installable, and folding the warning into `issues` would do exactly
    # that (any non-empty issue list means ok=$false here).
    param(
        [hashtable]$Config,
        [string]$CodexPath = '',
        [string]$KeeperRoot = '',
        [string]$Stage = 'Install'
    )
    $out = @{
        attempted  = $false
        armed      = $false
        validation = ''
        profile    = $null
        issues     = @()
        warnings   = @()
        cache      = $null
    }
    if ($null -eq $Config) { return $out }
    $armed = Test-AutoAnchorArmed $Config
    $out.armed = $armed

    $workDir = Join-Path (Get-RuntimeDir $KeeperRoot) 'anchor-work'
    Ensure-Directory $workDir | Out-Null
    $prof = Resolve-ExecutionProfile -Config $Config -CodexPath $CodexPath -WorkingDirectory $workDir
    $out.attempted = $true
    $out.profile = $prof
    $out.validation = [string]$prof.validation

    $aa = Get-AutoAnchorConfig $Config
    $configured = "codex.autoAnchor.model='$($aa.model)' reasoningEffort='$($aa.reasoningEffort)'"
    if ($prof.validation -eq 'VALID') {
        # Nothing to report, but do leave the panel something to show offline
        # (§14.1): this is the freshest verified profile anyone has taken.
        $out.cache = Write-ExecutionProfileCache -KeeperRoot $KeeperRoot -Profile $prof
        return $out
    }
    if ($prof.validation -eq 'INVALID') {
        $out.cache = Write-ExecutionProfileCache -KeeperRoot $KeeperRoot -Profile $prof
    }
    # UNAVAILABLE deliberately does NOT touch the cache: a read failure says
    # nothing about the profile, and overwriting the last real verdict with it
    # would make the offline status panel lie about a profile that was fine.
    $text = "execution profile could not be verified ($($prof.errorKind)): $($prof.validationReason)"
    if ($prof.validation -eq 'INVALID') {
        $text = "execution profile is invalid: $($prof.validationReason)"
    }
    if ($armed) {
        $tail = 'the task was not registered'
        if ($Stage -ne 'Install') { $tail = 'the existing scheduled task was left unchanged' }
        $out.issues += "AutoAnchor is armed but its $text ($configured). Fix codex.autoAnchor.model / reasoningEffort or the Codex CLI config they inherit; $tail."
        return $out
    }
    $out.warnings += "AutoAnchor is not armed, so its $text ($configured). Warning only: no model call is configured, nothing here blocks $Stage."
    return $out
}

function Get-ExecutionProfileGateSummary {
    # One line for the install/apply console: what the keeper will actually run,
    # and whether anyone checked. A gate that only ever speaks when it fails
    # leaves the operator unable to tell "verified good" from "never looked".
    param($Gate)
    if ($null -eq $Gate -or -not $Gate.attempted) { return 'not checked (environment validation failed first)' }
    $prof = $Gate.profile
    $state = if ($Gate.armed) { 'armed' } else { 'not armed' }
    if ($prof.validation -ne 'VALID') {
        $reason = [string]$prof.validationReason
        if ($reason.Length -gt 160) { $reason = $reason.Substring(0, 157) + '...' }
        return "$($prof.validation) [$state] - $reason"
    }
    # An empty effort is a legitimate VALID answer (the model declares no default
    # and the config says nothing), so it gets a word rather than a blank.
    $effort = [string]$prof.effectiveReasoningEffort
    if (-not $effort) { $effort = 'cli-default' }
    return "VALID [$state] - $($prof.effectiveModel) / $effort (source: $($prof.modelSource))"
}

function Invoke-KeeperInstallProbe {
    param([hashtable]$Config, [string]$CodexPath)
    $attempts = 0
    for ($round = 1; $round -le 2; $round++) {
        $result = Invoke-CodexRateLimitsRead -Config $Config -CodexPath $CodexPath
        $attempts += [int]$result.attempts
        $result.rounds = $round
        $result.totalAttempts = $attempts
        if ($result.ok -or -not $result.retryable -or
            $result.errorKind -notin @('NETWORK_ERROR', 'TIMEOUT', 'EOF') -or $round -eq 2) { return $result }
        Start-Sleep -Seconds 2
    }
}

function Invoke-KeeperInstall {
    # Returns @{ ok; issues; warnings; taskName; machine; probe; codexPath }
    param(
        [string]$KeeperRoot = '',
        [string]$ConfigFile = '',
        [switch]$SkipProbe
    )
    $configIssues = @()
    $issues = @()
    $warnings = @()
    # Set when a config is needed; -SkipProbe skips the read that would otherwise
    # load it, so every later use has to test for null instead of assuming.
    $loaded = $null
    if (-not $KeeperRoot) { $KeeperRoot = Get-KeeperRoot }
    if (-not $ConfigFile) { $ConfigFile = Get-ConfigPath $KeeperRoot }

    $configCheck = Load-Config $ConfigFile
    $configIssues = @($configCheck.issues)

    # 1. Environment validation (PS version, git, codex, repo whitelist, runtime).
    $pf = Invoke-Preflight -Config $null -ConfigPath $ConfigFile -KeeperRoot $KeeperRoot
    if ($null -eq $pf -or -not $pf.machine) {
        return @{ configIssues = $configIssues; ok = $false; issues = $(if ($pf -and $pf.issues) { @($pf.issues) } else { @('preflight failed before producing a machine identity') }); warnings = @(); profile = $null; taskName = $null; machine = $null; probe = $null; codexPath = $null }
    }
    $issues += $pf.issues
    if ($PSVersionTable.PSVersion.Major -lt 5) {
        $issues += 'PowerShell 5.1 or newer is required'
    }

    # 2. Read-only connectivity probe (never calls the model).
    $probe = $null
    if (-not $SkipProbe -and $pf.codexPath -and $issues.Count -eq 0) {
        $loaded = Load-Config $ConfigFile
        $probe = Invoke-KeeperInstallProbe -Config $loaded.config -CodexPath $pf.codexPath
        if (-not $probe.ok) {
            $issues += "quota probe failed ($($probe.errorKind)): $($probe.message)"
        }
    }

    # 3. Execution profile gate (doc v3.0 §7). Deliberately after the checks above
    # and BEFORE the issue-list return below: a blocking profile therefore stops
    # the registration without having touched Task Scheduler at all. Skipped when
    # an earlier check already failed - there is no point opening an app-server
    # session in an environment that is known-broken, and the install is blocked
    # either way. -SkipProbe does NOT skip this: §14.1 makes Install/Apply live
    # validation, and a bypassable gate is not a gate.
    $gate = $null
    if ($pf.codexPath -and $issues.Count -eq 0) {
        if ($null -eq $loaded) { $loaded = Load-Config $ConfigFile }
        $gate = Get-ExecutionProfileGate -Config $loaded.config -CodexPath $pf.codexPath -KeeperRoot $KeeperRoot -Stage 'Install'
        $issues += $gate.issues
        $warnings += $gate.warnings
    }

    if ($issues.Count -gt 0) {
        return @{ configIssues = $configIssues; ok = $false; issues = $issues; warnings = $warnings; profile = $gate; taskName = $null; machine = $pf.machine; probe = $probe; codexPath = $pf.codexPath }
    }

    # 4. Machine identity already ensured by preflight (random UUID + label).

    # 5/6. Register the per-user scheduled task.
    if ($null -eq $loaded) { $loaded = Load-Config $ConfigFile }
    $taskName = Register-KeeperTask -Config $loaded.config -KeeperRoot $KeeperRoot -ConfigFile $ConfigFile
    $forcedAnchor = Invoke-ForcedAnchorIfRequested -Config $loaded.config -KeeperRoot $KeeperRoot -ConfigFile $ConfigFile

    return @{ configIssues = $configIssues; ok = $true; issues = @(); warnings = $warnings; profile = $gate; taskName = $taskName; machine = $pf.machine; probe = $probe; codexPath = $pf.codexPath; forcedAnchor = $forcedAnchor }
}

function Get-InstallPreflightLines {
    param($Result, [switch]$Detailed, [switch]$SkipProbe)
    $lines = @('Codex Quota Keeper - 安装检查', '')
    $lines += '【配置文件】'
    if (@($Result.configIssues).Count -gt 0) {
        $lines += '  [异常] 配置未通过校验，请修改后重试'
        foreach ($issue in $Result.configIssues) { $lines += "  $(Hide-SensitiveText $issue)" }
    } else { $lines += '  [正常] 配置格式及参数关系有效' }
    $lines += '【Codex CLI】'
    $lines += $(if ($Result.codexPath) { '  [正常] 已找到 Codex 命令' } else { '  [异常] 未找到；请安装 Codex CLI 或设置 codex.command' })
    $lines += '【AutoAnchor 执行配置】'
    $gate = $Result.profile
    if (-not $gate -or -not $gate.attempted) { $lines += '  [注意] 未执行校验，请先解决前置检查问题' }
    elseif ($gate.validation -eq 'VALID') { $lines += '  [正常] 模型与思考等级校验通过' }
    elseif ($gate.armed) { $lines += '  [异常] 执行配置不支持或暂时不可校验；自动锚定已阻止' }
    else { $lines += '  [注意] 执行配置未通过；当前不会自动调用模型，可继续只读监控' }
    $lines += '【额度接口】'
    if ($SkipProbe) { $lines += '  [注意] 已按 -SkipProbe 跳过额度探测' }
    elseif (-not $Result.probe) { $lines += '  [注意] 前置检查未通过，尚未探测' }
    elseif ($Result.probe.ok) { $lines += "  [正常] 只读连接成功（共 $($Result.probe.totalAttempts) 次连接尝试）" }
    else {
        $hint = switch ($Result.probe.errorKind) {
            'AUTH_ERROR' { '请在 Codex 中重新登录' }
            'RATE_LIMITED' { '请求被限流，请等待退避后重试' }
            'SCHEMA_UNKNOWN' { '接口结构无法识别，请检查 CLI 兼容版本' }
            'NETWORK_ERROR' { '网络连接失败，请检查代理、网络与证书' }
            'TIMEOUT' { '连接超时，请检查网络后重试' }
            'EOF' { '连接提前关闭，请检查 CLI 与代理' }
            default { '接口调用失败；使用 -Detailed 查看详情' }
        }
        $lines += "  [异常] $hint（$($Result.probe.errorKind)）"
    }
    $lines += '【计划任务】'
    $lines += $(if ($Result.ok) { "  [正常] 已注册：$($Result.taskName)" } else { '  [异常] 未注册，请解决上述问题后重新安装' })
    if ($Result.forcedAnchor.started) { $lines += '  [注意] 已按 anchorOnApply 配置提交立即锚定请求' }
    if ($Detailed) {
        $lines += '【详细信息】'
        foreach ($issue in @($Result.issues) + @($Result.warnings)) { $lines += "  $(Hide-SensitiveText $issue)" }
        if ($gate) { $lines += "  $(Hide-SensitiveText (Get-ExecutionProfileGateSummary $gate))" }
    }
    return ,$lines
}

if ($MyInvocation.InvocationName -ne '.') {
    try { $result = Invoke-KeeperInstall -KeeperRoot $KeeperRoot -ConfigFile $ConfigFile -SkipProbe:$SkipProbe }
    catch {
        $result = @{ ok = $false; issues = @((Hide-SensitiveText $_.Exception.Message)); configIssues = @(); warnings = @() }
    }
    Get-InstallPreflightLines -Result $result -SkipProbe:$SkipProbe -Detailed:$Detailed | ForEach-Object { $_ | ForEach-Object { Write-Host $_ } }
    exit $(if ($result.ok) { 0 } else { 1 })
}
